settings:
  title: 'Hash Hackers Staus'
  url: 'https://status.hashhackers.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All Good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: hashhackers-com
    name: hashhackers-com
    description: 'Hash Hackers Blog'
    url: 'https://hashhackers-com'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: decrypt-hashhackers-com # unique identifier
    name: decrypt.hashhackers.com
    description: 'Google Drive Sharer/Copy App' # default=empty
    url: 'https://decrypt.hashhackers.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: encrypt-hashhackers-com # unique identifier
    name: encrypt.hashhackers.com
    description: 'Google Drive Encrypt Links App' # default=empty
    url: 'https://encrypt.hashhackers.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: decryptionserver-hashhackers-com # unique identifier
    name: decryptionserver.hashhackers.com
    description: 'Decryption Server for Google Drive Sharer/Copy App' # default=empty
    url: 'https://decryptionserver.hashhackers.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: bay-index # unique identifier
    name: Public Bay Index Site
    description: 'Public Bay Index Site (Not HH)' # default=empty
    url: 'https://1002esfejqd5pdn06jh689akutte5019btlp0o4o6bcr56uogho1fso.fileportal.org' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: telegram-api # unique identifier
    name: Public Telegram API
    description: 'Public Telegram API (Not HH)' # default=empty
    url: 'https://api.telegram.org/bot' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: telegram-api # unique identifier
    name: Public Telegram API
    description: 'Public Telegram API (Not HH)' # default=empty
    url: 'https://api.telegram.org/bot' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
