settings:
  title: 'HHS'
  url: 'https://status.hashhackers.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All Good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: hashhackers-com-blog
    name: HH Blog
    description: 'Blog'
    url: 'https://hashhackers.com'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: decrypt-hashhackers-com # unique identifier
    name: Decrypt
    description: 'Sharer App' # default=empty
    url: 'https://decrypt.hashhackers.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: encrypt-hashhackers-com # unique identifier
    name: Encrypt
    description: 'Encrypt Links' # default=empty
    url: 'https://encrypt.hashhackers.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: decryptionserver-hashhackers-com # unique identifier
    name: DecryptionS
    description: 'Decryption Server for Google Drive Sharer/Copy App' # default=empty
    url: 'https://decryptionserver.hashhackers.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: bay-index # unique identifier
    name: theindex.eu.org
    description: 'The Index' # default=empty
    url: 'https://theindex.eu.org' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: hindi-index # unique identifier
    name: simpleprogram.eu.org
    description: 'Hindi Index' # default=empty
    url: 'https://simpleprogram.eu.org' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: telegram-api # unique identifier
    name: Telegram API
    description: 'Telegram API' # default=empty
    url: 'https://api.telegram.org/bot' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: five-rapidleech-gq # unique identifier
    name: five.rapidleech.gq
    description: 'Rapidleech Server Heroku' # default=empty
    url: 'https://five.rapidleech.gq' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ten-rapidleech-gq # unique identifier
    name: ten.rapidleech.gq
    description: 'Rapidleech Server Heroku' # default=empty
    url: 'https://ten.rapidleech.gq' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: twenty-rapidleech-gq # unique identifier
    name: twenty.rapidleech.gq
    description: 'Rapidleech Server Heroku' # default=empty
    url: 'https://twenty.rapidleech.gq' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: eu-frankfurt-rapidleech-gq # unique identifier
    name: Rapidleech FR
    description: 'Rapidleech Server Oracle' # default=empty
    url: 'https://eu-frankfurt.rapidleech.gq' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: eu-amsterdam-rapidleech-gq # unique identifier
    name: Rapidleech AD
    description: 'Rapidleech Server Oracle' # default=empty
    url: 'https://eu-amsterdam.rapidleech.gq' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: www-1337x-to-workers-dev # unique identifier
    name: 1337x Proxy
    description: '1337x Proxy Server' # default=empty
    url: 'https://www.1337x-to.workers.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: cdn-7 # unique identifier
    name: cdn-7
    description: '' # default=empty
    url: 'https://proxy.cdn-7.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: cdn-8 # unique identifier
    name: cdn-8
    description: '' # default=empty
    url: 'https://proxy.cdn-8.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: indiadownloadserver3 # unique identifier
    name: indiadownloadserver3
    description: '' # default=empty
    url: 'https://proxy.indiadownloadserver3.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: indiadownloadserver4 # unique identifier
    name: indiadownloadserver4
    description: '' # default=empty
    url: 'https://proxy.indiadownloadserver4.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: indiadownloadserver5 # unique identifier
    name: indiadownloadserver5
    description: '' # default=empty
    url: 'https://proxy.indiadownloadserver5.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: indiadownloadserver6 # unique identifier
    name: indiadownloadserver6
    description: '' # default=empty
    url: 'https://proxy.indiadownloadserver6.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: europecdn # unique identifier
    name: europecdn
    description: '' # default=empty
    url: 'https://proxy.europecdn.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: qcdn # unique identifier
    name: qcdn
    description: '' # default=empty
    url: 'https://proxy.qcdn.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: cdn-bhadoo-745 # unique identifier
    name: cdn-bhadoo-745
    description: '' # default=empty
    url: 'https://proxy.bhadoo-worldwide-simpleprogram-cdn-server-745.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: indiacdn # unique identifier
    name: indiacdn
    description: '' # default=empty
    url: 'https://proxy.indiacdn.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: antarctica # unique identifier
    name: antarctica
    description: '' # default=empty
    url: 'https://proxy.antarctica.workers.dev/download.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
